-- Body & nutrition snapshot fields for leads and contacts
ALTER TABLE leads
  ADD COLUMN IF NOT EXISTS age             INTEGER,
  ADD COLUMN IF NOT EXISTS height_cm       NUMERIC,
  ADD COLUMN IF NOT EXISTS weight_kg       NUMERIC,
  ADD COLUMN IF NOT EXISTS body_fat_pct    NUMERIC,
  ADD COLUMN IF NOT EXISTS muscle_mass_kg  NUMERIC,
  -- measurements (cm)
  ADD COLUMN IF NOT EXISTS neck_cm         NUMERIC,
  ADD COLUMN IF NOT EXISTS shoulders_cm    NUMERIC,
  ADD COLUMN IF NOT EXISTS chest_cm        NUMERIC,
  ADD COLUMN IF NOT EXISTS bicep_l_cm      NUMERIC,
  ADD COLUMN IF NOT EXISTS bicep_r_cm      NUMERIC,
  ADD COLUMN IF NOT EXISTS waist_cm        NUMERIC,
  ADD COLUMN IF NOT EXISTS hips_cm         NUMERIC,
  ADD COLUMN IF NOT EXISTS thigh_l_cm      NUMERIC,
  ADD COLUMN IF NOT EXISTS thigh_r_cm      NUMERIC,
  ADD COLUMN IF NOT EXISTS calf_l_cm       NUMERIC,
  ADD COLUMN IF NOT EXISTS calf_r_cm       NUMERIC,
  -- nutrition
  ADD COLUMN IF NOT EXISTS kcal_current    NUMERIC,
  ADD COLUMN IF NOT EXISTS protein_g       NUMERIC,
  ADD COLUMN IF NOT EXISTS carbs_g         NUMERIC,
  ADD COLUMN IF NOT EXISTS fat_g           NUMERIC,
  ADD COLUMN IF NOT EXISTS water_liters    NUMERIC,
  ADD COLUMN IF NOT EXISTS supplements     TEXT;

ALTER TABLE contacts
  ADD COLUMN IF NOT EXISTS age             INTEGER,
  ADD COLUMN IF NOT EXISTS height_cm       NUMERIC,
  ADD COLUMN IF NOT EXISTS weight_kg       NUMERIC,
  ADD COLUMN IF NOT EXISTS body_fat_pct    NUMERIC,
  ADD COLUMN IF NOT EXISTS muscle_mass_kg  NUMERIC,
  ADD COLUMN IF NOT EXISTS neck_cm         NUMERIC,
  ADD COLUMN IF NOT EXISTS shoulders_cm    NUMERIC,
  ADD COLUMN IF NOT EXISTS chest_cm        NUMERIC,
  ADD COLUMN IF NOT EXISTS bicep_l_cm      NUMERIC,
  ADD COLUMN IF NOT EXISTS bicep_r_cm      NUMERIC,
  ADD COLUMN IF NOT EXISTS waist_cm        NUMERIC,
  ADD COLUMN IF NOT EXISTS hips_cm         NUMERIC,
  ADD COLUMN IF NOT EXISTS thigh_l_cm      NUMERIC,
  ADD COLUMN IF NOT EXISTS thigh_r_cm      NUMERIC,
  ADD COLUMN IF NOT EXISTS calf_l_cm       NUMERIC,
  ADD COLUMN IF NOT EXISTS calf_r_cm       NUMERIC,
  ADD COLUMN IF NOT EXISTS kcal_current    NUMERIC,
  ADD COLUMN IF NOT EXISTS protein_g       NUMERIC,
  ADD COLUMN IF NOT EXISTS carbs_g         NUMERIC,
  ADD COLUMN IF NOT EXISTS fat_g           NUMERIC,
  ADD COLUMN IF NOT EXISTS water_liters    NUMERIC,
  ADD COLUMN IF NOT EXISTS supplements     TEXT;
